# This file is part of BenchExec, a framework for reliable benchmarking:
# https://github.com/sosy-lab/benchexec
#
# SPDX-FileCopyrightText: 2026 Dirk Beyer <https://www.sosy-lab.org>
#
# SPDX-License-Identifier: Apache-2.0

# Documentation:
# https://docs.zizmor.sh/configuration/
# https://docs.zizmor.sh/audits/

rules:
  unpinned-uses:
    config:
      policies:
        # We use only a limited set of actions of organizations we trust.
        # Immutable releases are likely an alternative in the future:
        # https://github.com/zizmorcore/zizmor/issues/766
        "*": ref-pin
