import React from 'react';
import ReactTable from 'react-table'
import 'react-table/react-table.css'
import withFixedColumns from 'react-table-hoc-fixed-columns';
import 'react-table-hoc-fixed-columns/lib/styles.css'

const ReactTableFixedColumns = withFixedColumns(ReactTable);

export default class Summary extends React.Component {

    constructor(props) {
        super(props);
        this.state= {
            showTotal: true,
            showLocal: true,
            showCorrect: true,
            showIncorrect: true,
            fixed: true,
        }
        this.infos = ['displayName', 'tool', 'limit', 'host', 'os', 'system', 'date', 'runset', 'branch', 'options', 'property'];
        this.width = (window.innerWidth*0.15);
    };

    renderResultTable = () => {
        return this.props.tools.map((tool, j) => {
            
            return tool.columns.map((column, i) => {
                
                return {
                    id: column.title+j,
                    Header: () => (
                        <div className="columns" title="Show Quantile Plot of this column" onClick={(e) => this.props.changeTab(e, column, 2)}>{column.title + (column.source_unit ? " (" + column.source_unit + ")" : '')}</div>
                        ),
                        show: column.isVisible,
                        accessor: props => (
                        props.content[j][i] ? <div className="summary_span">{this.props.prepareTableValues(props.content[j][i].sum, j, i)}</div> : <div className="summary_span">-</div>
                    ),
                }
            });
        });
    }
    handleInputChange = (event) => {
        const target = event.target;
        const value = target.checked;
        const name = target.name;
    
        this.setState({
          [name]: value
        });
    }

    render() {
        const toolColumns = this.renderResultTable();
        const column = [
            {
                Header: () => (
                    <div className="toolsHeader">
                        <form>
                            <label>
                                Fixed:
                            </label>
                            <input name="fixed" type="checkbox" checked={this.state.fixed} onChange={this.handleInputChange} />
                        </form>
                    </div>
                ),
                fixed: this.state.fixed ? 'left' : '',
                width: this.width,
                columns: [
                    {
                        id: 'summary',
                        width: this.width,
                        Header: () => (
                            <div
                                onClick={this.props.selectColumn}
                            >
                                <span>Click here to select columns</span>
                            </div>
                        ),
                        accessor: props => (
                            <div dangerouslySetInnerHTML={{ __html: props.title }} title={props.description} className="tr"/>
                        )
                    },
                ]
            },
            ...toolColumns.map((toolColumn, i) => {
                return {   
                    id: 'results',
                    Header: () => (
                        <div className="header__tool-infos">
                            {this.props.getRunSets(this.props.tools[i], i)}
                        </div>  
                    ),
                    columns: toolColumn
                };
            })
        ]

        return (
             <div className = "summary">
                 <h2>Toolinformation</h2>
                <table>
                    <tbody>
                        {this.infos.filter(info => this.props.tableHeader[info] !== null).map((row, i) => {
                            return  <tr key={'tr-'+row}> 
                                        <th key={'td-'+row}>{row}</th>
                                        {this.props.tableHeader[row].content.map((tool, j) => <td colSpan={tool[1]} key={tool[0]+j} className="header__tool-row">{tool[0]} </td>)}
                                    </tr>
                        })}
                    </tbody>
                </table>
                <h2>Summary</h2>
                <ReactTableFixedColumns
                    data={this.props.stats}
                    columns= {column}
                    showPagination={false}
                    className = "-highlight"
                    minRows = {0}
                    sortable = {false}
                />
                <p>Generated by <a className ="link" href="https://github.com/sosy-lab/benchexec" target="_blank" rel="noopener noreferrer"> BenchExec</a></p>
            </div>
        )
    }
}