// This file is part of BenchExec, a framework for reliable benchmarking:
// https://github.com/sosy-lab/benchexec
//
// SPDX-FileCopyrightText: 2019-2020 Dirk Beyer <https://www.sosy-lab.org>
//
// SPDX-License-Identifier: Apache-2.0

import React from "react";
import StatisticsTable from "./StatisticsTable";

/* ============================================================
 * Domain Types
 * ============================================================
 */

/**
 * A single header row entry in the benchmark setup table.
 * `content` is an array per tool/runset containing tuples of:
 * [displayTextOrPayload, colSpan].
 */
type TableHeaderRow = {
  id: string;
  name: string;
  content: Array<[unknown, number]>;
};

/**
 * Table header structure as used by Summary.
 * Keys are stable strings like "tool", "date", "options", ...
 */
type TableHeader = Record<string, TableHeaderRow | null>;

/**
 * Payload used by the "tool" row in the header table.
 * This matches the destructuring in renderToolNameAndVersion(...).
 */
type ToolVersionInfo = {
  tool: string;
  version: string;
  project_url?: string;
  version_url?: string;
};

/* ============================================================
 * Component Types
 * ============================================================
 */

type SummaryProps = {
  tableHeader: TableHeader;

  // passed through to StatisticsTable (typed locally only as far as Summary needs)
  selectColumn: (...args: unknown[]) => void;
  tools: unknown;
  switchToQuantile: (...args: unknown[]) => void;
  hiddenCols: unknown;
  tableData: unknown;
  onStatsReady: (...args: unknown[]) => void;
  stats: unknown;
  filtered: boolean;

  version: string;
};

const infos = [
  "displayName",
  "tool",
  "limit",
  "host",
  "os",
  "system",
  "date",
  "runset",
  "branch",
  "options",
  "property",
] as const;

const Summary = (props: SummaryProps): React.ReactElement => {
  /* ++++++++++++++ Helper functions ++++++++++++++ */

  const renderOptions = (text: string): React.ReactNode =>
    text.split(/[\s]+-/).map((option, i) => (
      <li key={option}>
        <code>{i === 0 ? option : `-${option}`}</code>
      </li>
    ));

  const externalLink = (
    url: string | undefined,
    text: string,
  ): React.ReactNode => {
    if (url) {
      return (
        <a href={url} target="_blank" rel="noopener noreferrer">
          {text}
        </a>
      );
    } else {
      return text;
    }
  };

  const renderToolNameAndVersion = ({
    tool,
    version,
    project_url,
    version_url,
  }: ToolVersionInfo): React.ReactNode => {
    return (
      <>
        {externalLink(project_url, tool)} {externalLink(version_url, version)}
      </>
    );
  };

  /* ++++++++++++++ Table render functions ++++++++++++++ */

  const renderRow = (
    row: string,
    text: unknown,
    colSpan: number,
    j: number,
  ): React.ReactElement => {
    const isOptionRow = row === "options";
    const isToolRow = row === "tool";

    return (
      <td
        colSpan={colSpan}
        key={String((typeof text === "string" ? text : row) + j)}
        className={`header__tool-row${isOptionRow && " options"}`}
      >
        {isOptionRow ? (
          <ul>{renderOptions(String(text))}</ul>
        ) : isToolRow ? (
          renderToolNameAndVersion(text as ToolVersionInfo)
        ) : (
          String(text)
        )}
      </td>
    );
  };

  return (
    <div id="summary">
      <div id="benchmark_setup">
        <h2>Benchmark Setup</h2>
        <table>
          <tbody>
            {infos
              .map((row) => props.tableHeader[row])
              .filter((row): row is TableHeaderRow => row !== null)
              .map((row) => (
                <tr key={"tr-" + row.id} className={row.id}>
                  <th key={"td-" + row.id}>{row.name}</th>
                  {row.content.map((tool, j) =>
                    renderRow(row.id, tool[0], tool[1], j),
                  )}
                </tr>
              ))}
          </tbody>
        </table>
      </div>
      <StatisticsTable
        selectColumn={props.selectColumn}
        tools={props.tools}
        switchToQuantile={props.switchToQuantile}
        hiddenCols={props.hiddenCols}
        tableData={props.tableData}
        onStatsReady={props.onStatsReady}
        stats={props.stats}
        filtered={props.filtered}
      />
      <p>
        Generated by{" "}
        <a
          className="link"
          href="https://github.com/sosy-lab/benchexec"
          target="_blank"
          rel="noopener noreferrer"
        >
          {" "}
          BenchExec {props.version}
        </a>
      </p>
    </div>
  );
};

export default Summary;
