#!/bin/sh

# This file is part of BenchExec, a framework for reliable benchmarking:
# https://github.com/sosy-lab/benchexec
#
# SPDX-FileCopyrightText: 2019-2020 Dirk Beyer <https://www.sosy-lab.org>
#
# SPDX-License-Identifier: Apache-2.0

set -e

GROUP=benchexec

add_group() {
  addgroup --system "${GROUP}"
  echo
  echo "Please add those user accounts that should be able to use BenchExec to the group ${GROUP}."
  echo
}

case "$1" in
  configure)
    add_group
    ;;
esac

#DEBHELPER#
